In [1]:
# To be able to make edits to repo without having to restart notebook
%load_ext autoreload
%autoreload 2

In [2]:
import os, sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import pearsonr, mannwhitneyu, wilcoxon, ttest_rel, ttest_ind
import seaborn as sns
from matplotlib.patches import FancyArrowPatch
from matplotlib.colors import ColorConverter

remap_path = os.getcwd()
prototype_path = os.path.abspath(os.path.join(remap_path, os.pardir))
project_path = os.path.abspath(os.path.join(prototype_path, os.pardir))
lab_path = os.path.abspath(os.path.join(project_path, os.pardir))
sys.path.append(project_path)
os.chdir(project_path)
sys.path.append(project_path)
print(project_path)

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit

In [3]:
from scripts.batch_map.LEC_naming import LEC_naming_format, extract_name_lec

In [4]:
ANT_path = r"C:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit_test_data\LEC_remapping\ANT"
NON_path = r"C:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit_test_data\LEC_remapping\NON"
B6_path = r"C:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit_test_data\LEC_remapping\B6"
dfs = []
for path in [ANT_path, NON_path, B6_path]:
    for animal_dir in os.listdir(path):
        for csv_file in os.listdir(path + r'\\' + animal_dir):
            if csv_file.endswith('.xlsx'):
                file_df = pd.read_excel(path + r'\\' + animal_dir + r'\\' + csv_file)
                # add column for genotype
                if path == ANT_path:
                    file_df['group'] = 'ANT'
                elif path == NON_path:
                    file_df['group'] = 'NON'
                elif path == B6_path:
                    file_df['group'] = 'B6'
                dfs.append(file_df)

df_remapping = pd.concat(dfs, ignore_index=True)
df_remapping.columns

Index(['Unnamed: 0', 'signature', 'depth', 'name', 'date', 'tetrode',
       'unit_id', 'session_id', 'obj_pos', 'object_location', 'score',
       'field_id', 'field_count', 'obj_wass_0', 'obj_wass_90', 'obj_wass_180',
       'obj_wass_270', 'obj_wass_NO', 'obj_q_0', 'obj_q_90', 'obj_q_180',
       'obj_q_270', 'obj_q_NO', 'obj_vec_0', 'obj_vec_90', 'obj_vec_180',
       'obj_vec_270', 'obj_vec_NO', 'bin_area', 'total_rate',
       'field_peak_rate', 'spike_count', 'field_coverage', 'field_area',
       'field_rate', 'cumulative_coverage', 'cumulative_area',
       'cumulative_rate', 'arena_size', 'cylinder', 'ratemap_dims', 'spacing',
       'hexagonal', 'sample_size', 'downsample_factor', 'group'],
      dtype='object')

In [5]:
# Match remapping csvs to neurofunc csvss

ANT_path = r"C:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit_test_data\LEC_neurofunc\ANT"
NON_path = r"C:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit_test_data\LEC_neurofunc\NON"
B6_path = r"C:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit_test_data\LEC_neurofunc\B6"
dfs = []
for path in [ANT_path, NON_path, B6_path]:
    for csv_file in os.listdir(path):
        if csv_file.endswith('.xlsx') and '~$' not in csv_file:
            print(csv_file)
            file_df = pd.read_excel(path + r'\\' + csv_file)
            name = csv_file.split('_')[0]
            for i, row in file_df.iterrows():
                signature = row['Session']
                # print(name)
                if name not in signature:
                    signature = name + '_' + signature
                    file_df.at[i, 'Session'] = signature

            # add column for genotype
            if path == ANT_path:
                file_df['group'] = 'ANT'
            elif path == NON_path:
                file_df['group'] = 'NON'
            elif path == B6_path:
                file_df['group'] = 'B6'
            dfs.append(file_df)

df_neurofunc = pd.concat(dfs, ignore_index=True)

from datetime import datetime

NON_set_path = r"C:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit_test_data\LEC_set_files\NON"
ANT_set_path = r"C:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit_test_data\LEC_set_files\ANT"
B6_set_path = r"C:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit_test_data\LEC_set_files\B6"
# insert column for date_time into df_neurofunc
df_neurofunc['date_time'] = pd.NaT
df_neurofunc['ses_ct'] = pd.NaT

for path in [ANT_set_path, NON_set_path, B6_set_path]:
    for animal_dir in os.listdir(path):
        for set_dir in os.listdir(path + r'\\' + animal_dir):
            date_times = {}
            # sigs = []
            for set_file in os.listdir(path + r'\\' + animal_dir + r'\\' + set_dir):
                # print(set_file)
                assert set_file.endswith('.set')
                ses_signature = set_file.split('.')[0]

                # sigs.append(ses_signature)
                # print(set_file)
                with open(path + r'\\' + animal_dir + r'\\' + set_dir + r'\\' + set_file, 'r') as f:
                    for line in f:
                        if 'trial_time' in str(line):
                            # trial_time = line.decode(encoding='UTF-8').split(" ")[1]
                            trial_time = line.split(" ")[1]
                        if 'trial_date' in str(line):
                            trial_date = line.split(" ")[2:]

                    day, month, year = trial_date
                    month = datetime.strptime(str(month), '%b').month
                    hour, minute, second = trial_time.split(':')
                    date_time = datetime(int(year), int(month), int(day), int(hour), int(minute), int(second))

                # assert ses_signature not in date_times.keys(), 'Session signature {} already in dictionary'.format(ses_signature)
                # assert date_time not in date_times.values(), 'Date time {} already in dictionary'.format(date_time) 
                date_times[ses_signature] = date_time

                print(date_time, ses_signature)

            # sort dictionary by date_time
            sigs = list(date_times.keys())
            date_times = list(date_times.values())
            sorted_sigs = [x for _, x in sorted(zip(date_times, sigs))]
            date_times = sorted(date_times)
            # # argsort 
            # sorted_sigs = [x for _, x in sorted(zip(date_times, sigs))]
            print(date_times, sorted_sigs)
            ses_ct = 1
            # print(sorted_sigs)
            for ses in sorted_sigs:

                if len(df_neurofunc[df_neurofunc['Session'] == ses]) == 0:
                    pass
                else:
                    # add date time column
                    df_neurofunc.loc[df_neurofunc['Session'] == ses, 'date_time'] = date_times[ses_ct - 1]
                    df_neurofunc.loc[df_neurofunc['Session'] == ses, 'ses_ct'] = ses_ct
                    ses_ct += 1

print(df_neurofunc.columns)

ANT-119a-6_missing_combined.xlsx
ANT-119a-6_Unit Matched_combined.xlsx
ANT-120-4_matched_combined.xlsx
ANT-133a-4_matched_combined.xlsx
ANT-135a-7_missing_combined.xlsx
ANT-135a-7_Unit Matched_combined.xlsx
ANT-140-4_20180621_summary_sheet_1.xlsx
ANT-140-4_Unit Matched_combined.xlsx
NON-73-6_Unit Matched_combined.xlsx
NON-88-1_missing_combined.xlsx
NON-88-1_Unit Matched_combined.xlsx
NON-INT-01_Unit Matched_combined.xlsx
NON-INT-02_missing_combined.xlsx
NON-INT-02_Unit Matched_combined.xlsx
NON-INT-03_20170228_summary_sheet_1.xlsx
NON-INT-03_Unit Matched_combined.xlsx
B6-1M_matched_combined.xlsx
B6-1M_missing_combined.xlsx
B6-2M_matched_combined.xlsx
B6-2M_missing_combined.xlsx
B6-LEC1_,missing_combined.xlsx
B6-LEC1_matched_combined.xlsx
B6-LEC2_20160112_summary_sheet_1.xlsx
B6-LEC2_matched_combined.xlsx
B6-LEC2_missing_combined.xlsx
B6-LEC2_more_missing_combined.xlsx
2017-06-05 14:51:07 ANT-119a-6_20170605-3050-0
2017-06-05 14:28:49 ANT-119a-6_20170605-3050-270
2017-06-05 12:25:03 ANT-119a-6_20170605-3050-NO
[datetime.datetime(2017, 6, 5, 12, 25, 3), datetime.datetime(2017, 6, 5, 14, 28, 49), datetime.datetime(2017, 6, 5, 14, 51, 7)] ['ANT-119a-6_20170605-3050-NO', 'ANT-119a-6_20170605-3050-270', 'ANT-119a-6_20170605-3050-0']
2017-06-06 14:16:48 ANT-119a-6_20170606-3100-0
2017-06-06 14:31:48 ANT-119a-6_20170606-3100-90
2017-06-06 11:06:50 ANT-119a-6_20170606-3100-NO
[datetime.datetime(2017, 6, 6, 11, 6, 50), datetime.datetime(2017, 6, 6, 14, 16, 48), datetime.datetime(2017, 6, 6, 14, 31, 48)] ['ANT-119a-6_20170606-3100-NO', 'ANT-119a-6_20170606-3100-0', 'ANT-119a-6_20170606-3100-90']
2017-06-07 13:57:38 ANT-119a-6_20170607-3150-180
2017-06-07 13:43:59 ANT-119a-6_20170607-3150-90
2017-06-07 10:28:23 ANT-119a-6_20170607-3150-NO
[datetime.datetime(2017, 6, 7, 10, 28, 23), datetime.datetime(2017, 6, 7, 13, 43, 59), datetime.datetime(2017, 6, 7, 13, 57, 38)] ['ANT-119a-6_20170607-3150-NO', 'ANT-119a-6_20170607-3150-90', 'ANT-119a-6_20170607-3150-180']
2017-06-08 10:51:10 ANT-119a-6_20170608-3350-object180
2017-06-08 11:06:31 ANT-119a-6_20170608-3350-object270
[datetime.datetime(2017, 6, 8, 10, 51, 10), datetime.datetime(2017, 6, 8, 11, 6, 31)] ['ANT-119a-6_20170608-3350-object180', 'ANT-119a-6_20170608-3350-object270']
2017-06-09 10:50:40 ANT-119a-6_20170609-3400-180
2017-06-09 11:02:22 ANT-119a-6_20170609-3400-270
[datetime.datetime(2017, 6, 9, 10, 50, 40), datetime.datetime(2017, 6, 9, 11, 2, 22)] ['ANT-119a-6_20170609-3400-180', 'ANT-119a-6_20170609-3400-270']
2017-06-12 10:17:06 ANT-119a-6_20170612-3450-noodor-noobject
[datetime.datetime(2017, 6, 12, 10, 17, 6)] ['ANT-119a-6_20170612-3450-noodor-noobject']
2017-06-13 10:42:41 ANT-119a-6_20170613-2450-noodor-noobject
2017-06-13 10:58:15 ANT-119a-6_20170613-2450-object0
2017-06-13 11:26:32 ANT-119a-6_20170613-2450-object90
[datetime.datetime(2017, 6, 13, 10, 42, 41), datetime.datetime(2017, 6, 13, 10, 58, 15), datetime.datetime(2017, 6, 13, 11, 26, 32)] ['ANT-119a-6_20170613-2450-noodor-noobject', 'ANT-119a-6_20170613-2450-object0', 'ANT-119a-6_20170613-2450-object90']
2017-06-14 11:16:14 ANT-119a-6_20170614-2450-noodor-noobject
2017-06-14 11:41:59 ANT-119a-6_20170614-2450-object180
2017-06-14 11:28:37 ANT-119a-6_20170614-2450-object90
[datetime.datetime(2017, 6, 14, 11, 16, 14), datetime.datetime(2017, 6, 14, 11, 28, 37), datetime.datetime(2017, 6, 14, 11, 41, 59)] ['ANT-119a-6_20170614-2450-noodor-noobject', 'ANT-119a-6_20170614-2450-object90', 'ANT-119a-6_20170614-2450-object180']
2017-06-15 12:17:15 ANT-119a-6_20170615-2450-noodor-noobject
2017-06-15 12:34:32 ANT-119a-6_20170615-2450-object180
2017-06-15 12:56:35 ANT-119a-6_20170615-2450-object270
[datetime.datetime(2017, 6, 15, 12, 17, 15), datetime.datetime(2017, 6, 15, 12, 34, 32), datetime.datetime(2017, 6, 15, 12, 56, 35)] ['ANT-119a-6_20170615-2450-noodor-noobject', 'ANT-119a-6_20170615-2450-object180', 'ANT-119a-6_20170615-2450-object270']
2017-06-16 11:08:29 ANT-119a-6_20170616-2425-object0
2017-06-16 10:50:50 ANT-119a-6_20170616-2425-object270
[datetime.datetime(2017, 6, 16, 10, 50, 50), datetime.datetime(2017, 6, 16, 11, 8, 29)] ['ANT-119a-6_20170616-2425-object270', 'ANT-119a-6_20170616-2425-object0']
2017-06-19 11:46:43 ANT-119a-6_20170619-2375-noodor-noobject
2017-06-19 12:00:34 ANT-119a-6_20170619-2375-object270
2017-06-19 11:23:46 ANT-119a-6_20170619-2425-object0
2017-06-19 11:05:58 ANT-119a-6_20170619-2425-object270
[datetime.datetime(2017, 6, 19, 11, 5, 58), datetime.datetime(2017, 6, 19, 11, 23, 46), datetime.datetime(2017, 6, 19, 11, 46, 43), datetime.datetime(2017, 6, 19, 12, 0, 34)] ['ANT-119a-6_20170619-2425-object270', 'ANT-119a-6_20170619-2425-object0', 'ANT-119a-6_20170619-2375-noodor-noobject', 'ANT-119a-6_20170619-2375-object270']
2017-06-20 10:28:55 ANT-119a-6_20170620-2275-noodor-noobject
2017-06-20 10:59:12 ANT-119a-6_20170620-2275-object0
2017-06-20 10:44:59 ANT-119a-6_20170620-2275-object270
[datetime.datetime(2017, 6, 20, 10, 28, 55), datetime.datetime(2017, 6, 20, 10, 44, 59), datetime.datetime(2017, 6, 20, 10, 59, 12)] ['ANT-119a-6_20170620-2275-noodor-noobject', 'ANT-119a-6_20170620-2275-object270', 'ANT-119a-6_20170620-2275-object0']
2017-06-21 12:52:40 ANT-119a-6_20170621-2275-noodor-noobject
2017-06-21 13:05:33 ANT-119a-6_20170621-2275-object180
2017-06-21 13:20:07 ANT-119a-6_20170621-2275-object270
[datetime.datetime(2017, 6, 21, 12, 52, 40), datetime.datetime(2017, 6, 21, 13, 5, 33), datetime.datetime(2017, 6, 21, 13, 20, 7)] ['ANT-119a-6_20170621-2275-noodor-noobject', 'ANT-119a-6_20170621-2275-object180', 'ANT-119a-6_20170621-2275-object270']
2017-06-22 11:24:37 ANT-119a-6_20170622-2250-object0
2017-06-22 11:00:45 ANT-119a-6_20170622-2250-object270
[datetime.datetime(2017, 6, 22, 11, 0, 45), datetime.datetime(2017, 6, 22, 11, 24, 37)] ['ANT-119a-6_20170622-2250-object270', 'ANT-119a-6_20170622-2250-object0']
2017-06-23 10:59:02 ANT-119a-6_20170623-2250-object180
2017-06-23 10:45:43 ANT-119a-6_20170623-2250-object90
[datetime.datetime(2017, 6, 23, 10, 45, 43), datetime.datetime(2017, 6, 23, 10, 59, 2)] ['ANT-119a-6_20170623-2250-object90', 'ANT-119a-6_20170623-2250-object180']
2017-06-26 10:20:33 ANT-119a-6_20170626-2250-noodor-noobject
2017-06-26 10:43:26 ANT-119a-6_20170626-2250-object180
2017-06-26 10:57:20 ANT-119a-6_20170626-2250-object270
[datetime.datetime(2017, 6, 26, 10, 20, 33), datetime.datetime(2017, 6, 26, 10, 43, 26), datetime.datetime(2017, 6, 26, 10, 57, 20)] ['ANT-119a-6_20170626-2250-noodor-noobject', 'ANT-119a-6_20170626-2250-object180', 'ANT-119a-6_20170626-2250-object270']
2017-06-27 11:36:03 ANT-119a-6_20170627-2225-noodor-noobject
2017-06-27 11:23:39 ANT-119a-6_20170627-2225-object180
2017-06-27 11:07:44 ANT-119a-6_20170627-2225-object90
[datetime.datetime(2017, 6, 27, 11, 7, 44), datetime.datetime(2017, 6, 27, 11, 23, 39), datetime.datetime(2017, 6, 27, 11, 36, 3)] ['ANT-119a-6_20170627-2225-object90', 'ANT-119a-6_20170627-2225-object180', 'ANT-119a-6_20170627-2225-noodor-noobject']
2017-06-28 13:06:55 ANT-119a-6_20170628-2225-object0
2017-06-28 12:50:20 ANT-119a-6_20170628-2225-object270
[datetime.datetime(2017, 6, 28, 12, 50, 20), datetime.datetime(2017, 6, 28, 13, 6, 55)] ['ANT-119a-6_20170628-2225-object270', 'ANT-119a-6_20170628-2225-object0']
2017-06-29 12:22:32 ANT-119a-6_20170629-2200-noodor-noobject
2017-06-29 12:47:27 ANT-119a-6_20170629-2200-object180
2017-06-29 12:36:02 ANT-119a-6_20170629-2200-object90
[datetime.datetime(2017, 6, 29, 12, 22, 32), datetime.datetime(2017, 6, 29, 12, 36, 2), datetime.datetime(2017, 6, 29, 12, 47, 27)] ['ANT-119a-6_20170629-2200-noodor-noobject', 'ANT-119a-6_20170629-2200-object90', 'ANT-119a-6_20170629-2200-object180']
2017-06-30 11:02:28 ANT-119a-6_20170630-2200-noodor-noobject
2017-06-30 11:17:11 ANT-119a-6_20170630-2200-object180
2017-06-30 11:40:30 ANT-119a-6_20170630-2200-object270
[datetime.datetime(2017, 6, 30, 11, 2, 28), datetime.datetime(2017, 6, 30, 11, 17, 11), datetime.datetime(2017, 6, 30, 11, 40, 30)] ['ANT-119a-6_20170630-2200-noodor-noobject', 'ANT-119a-6_20170630-2200-object180', 'ANT-119a-6_20170630-2200-object270']
2017-07-03 12:37:22 ANT-119a-6_20170703-2175-noodor-noobject
2017-07-03 12:55:05 ANT-119a-6_20170703-2175-object0
2017-07-03 13:07:29 ANT-119a-6_20170703-2175-object90
[datetime.datetime(2017, 7, 3, 12, 37, 22), datetime.datetime(2017, 7, 3, 12, 55, 5), datetime.datetime(2017, 7, 3, 13, 7, 29)] ['ANT-119a-6_20170703-2175-noodor-noobject', 'ANT-119a-6_20170703-2175-object0', 'ANT-119a-6_20170703-2175-object90']
2017-07-05 10:18:21 ANT-119a-6_20170705-2175-noodor-noobject
2017-07-05 10:44:53 ANT-119a-6_20170705-2175-object180
2017-07-05 10:32:07 ANT-119a-6_20170705-2175-object90
[datetime.datetime(2017, 7, 5, 10, 18, 21), datetime.datetime(2017, 7, 5, 10, 32, 7), datetime.datetime(2017, 7, 5, 10, 44, 53)] ['ANT-119a-6_20170705-2175-noodor-noobject', 'ANT-119a-6_20170705-2175-object90', 'ANT-119a-6_20170705-2175-object180']
2017-07-06 13:33:02 ANT-119a-6_20170706-2150-noodor-noobject
2017-07-06 13:59:18 ANT-119a-6_20170706-2150-object0
2017-07-06 13:44:49 ANT-119a-6_20170706-2150-object270
[datetime.datetime(2017, 7, 6, 13, 33, 2), datetime.datetime(2017, 7, 6, 13, 44, 49), datetime.datetime(2017, 7, 6, 13, 59, 18)] ['ANT-119a-6_20170706-2150-noodor-noobject', 'ANT-119a-6_20170706-2150-object270', 'ANT-119a-6_20170706-2150-object0']
2017-07-07 09:52:12 ANT-119a-6_20170707-2150-noodor-noobject
2017-07-07 10:04:34 ANT-119a-6_20170707-2150-object0
2017-07-07 10:19:12 ANT-119a-6_20170707-2150-object90
[datetime.datetime(2017, 7, 7, 9, 52, 12), datetime.datetime(2017, 7, 7, 10, 4, 34), datetime.datetime(2017, 7, 7, 10, 19, 12)] ['ANT-119a-6_20170707-2150-noodor-noobject', 'ANT-119a-6_20170707-2150-object0', 'ANT-119a-6_20170707-2150-object90']
2017-07-10 10:33:55 ANT-119a-6_20170710-2150-noodor-noobject
2017-07-10 10:51:54 ANT-119a-6_20170710-2150-object180
2017-07-10 11:21:37 ANT-119a-6_20170710-2150-object270
[datetime.datetime(2017, 7, 10, 10, 33, 55), datetime.datetime(2017, 7, 10, 10, 51, 54), datetime.datetime(2017, 7, 10, 11, 21, 37)] ['ANT-119a-6_20170710-2150-noodor-noobject', 'ANT-119a-6_20170710-2150-object180', 'ANT-119a-6_20170710-2150-object270']
2017-07-11 14:43:44 ANT-119a-6_20170711-2150-180
2017-07-11 14:30:39 ANT-119a-6_20170711-2150-90
2017-07-11 14:19:47 ANT-119a-6_20170711-2150-NO
[datetime.datetime(2017, 7, 11, 14, 19, 47), datetime.datetime(2017, 7, 11, 14, 30, 39), datetime.datetime(2017, 7, 11, 14, 43, 44)] ['ANT-119a-6_20170711-2150-NO', 'ANT-119a-6_20170711-2150-90', 'ANT-119a-6_20170711-2150-180']
2017-07-13 13:47:19 ANT-119a-6_20170713-2150-180
2017-07-13 13:59:15 ANT-119a-6_20170713-2150-270
2017-07-13 13:33:19 ANT-119a-6_20170713-2150-NO
[datetime.datetime(2017, 7, 13, 13, 33, 19), datetime.datetime(2017, 7, 13, 13, 47, 19), datetime.datetime(2017, 7, 13, 13, 59, 15)] ['ANT-119a-6_20170713-2150-NO', 'ANT-119a-6_20170713-2150-180', 'ANT-119a-6_20170713-2150-270']
2017-07-14 13:25:09 ANT-119a-6_20170714-2150-object0
2017-07-14 13:39:40 ANT-119a-6_20170714-2150-object90
[datetime.datetime(2017, 7, 14, 13, 25, 9), datetime.datetime(2017, 7, 14, 13, 39, 40)] ['ANT-119a-6_20170714-2150-object0', 'ANT-119a-6_20170714-2150-object90']
2017-07-17 11:42:33 ANT-119a-6_20170717-2125-noodor-noobject
2017-07-17 12:25:32 ANT-119a-6_20170717-2125-object180
2017-07-17 12:41:00 ANT-119a-6_20170717-2125-object270
[datetime.datetime(2017, 7, 17, 11, 42, 33), datetime.datetime(2017, 7, 17, 12, 25, 32), datetime.datetime(2017, 7, 17, 12, 41)] ['ANT-119a-6_20170717-2125-noodor-noobject', 'ANT-119a-6_20170717-2125-object180', 'ANT-119a-6_20170717-2125-object270']
2017-07-18 11:12:20 ANT-119a-6_20170718-2125-noodor-noobject
2017-07-18 12:53:48 ANT-119a-6_20170718-2125-object0
2017-07-18 13:11:26 ANT-119a-6_20170718-2125-object90
[datetime.datetime(2017, 7, 18, 11, 12, 20), datetime.datetime(2017, 7, 18, 12, 53, 48), datetime.datetime(2017, 7, 18, 13, 11, 26)] ['ANT-119a-6_20170718-2125-noodor-noobject', 'ANT-119a-6_20170718-2125-object0', 'ANT-119a-6_20170718-2125-object90']
2017-07-05 10:58:43 ANT-120-4_20170705-2500-noodor-noobject
2017-07-05 11:37:58 ANT-120-4_20170705-2500-object180
2017-07-05 11:25:40 ANT-120-4_20170705-2500-object90
[datetime.datetime(2017, 7, 5, 10, 58, 43), datetime.datetime(2017, 7, 5, 11, 25, 40), datetime.datetime(2017, 7, 5, 11, 37, 58)] ['ANT-120-4_20170705-2500-noodor-noobject', 'ANT-120-4_20170705-2500-object90', 'ANT-120-4_20170705-2500-object180']
2017-07-06 10:32:43 ANT-120-4_20170706-2525-noodor-noobject
2017-07-06 10:44:09 ANT-120-4_20170706-2525-object180
2017-07-06 11:23:39 ANT-120-4_20170706-2525-object270
[datetime.datetime(2017, 7, 6, 10, 32, 43), datetime.datetime(2017, 7, 6, 10, 44, 9), datetime.datetime(2017, 7, 6, 11, 23, 39)] ['ANT-120-4_20170706-2525-noodor-noobject', 'ANT-120-4_20170706-2525-object180', 'ANT-120-4_20170706-2525-object270']
2017-07-07 10:32:18 ANT-120-4_20170707-2525-noodor-noobject
2017-07-07 11:03:04 ANT-120-4_20170707-2525-object180
2017-07-07 10:52:03 ANT-120-4_20170707-2525-object90
[datetime.datetime(2017, 7, 7, 10, 32, 18), datetime.datetime(2017, 7, 7, 10, 52, 3), datetime.datetime(2017, 7, 7, 11, 3, 4)] ['ANT-120-4_20170707-2525-noodor-noobject', 'ANT-120-4_20170707-2525-object90', 'ANT-120-4_20170707-2525-object180']
2017-07-10 13:06:38 ANT-120-4_20170710-2525-noodor-noobject
2017-07-10 13:35:10 ANT-120-4_20170710-2525-object0
2017-07-10 13:18:41 ANT-120-4_20170710-2525-object270
[datetime.datetime(2017, 7, 10, 13, 6, 38), datetime.datetime(2017, 7, 10, 13, 18, 41), datetime.datetime(2017, 7, 10, 13, 35, 10)] ['ANT-120-4_20170710-2525-noodor-noobject', 'ANT-120-4_20170710-2525-object270', 'ANT-120-4_20170710-2525-object0']
2017-07-11 10:27:50 ANT-120-4_20170711-2550-noodor-noobject
2017-07-11 10:46:15 ANT-120-4_20170711-2550-object0
2017-07-11 10:57:46 ANT-120-4_20170711-2550-object90
[datetime.datetime(2017, 7, 11, 10, 27, 50), datetime.datetime(2017, 7, 11, 10, 46, 15), datetime.datetime(2017, 7, 11, 10, 57, 46)] ['ANT-120-4_20170711-2550-noodor-noobject', 'ANT-120-4_20170711-2550-object0', 'ANT-120-4_20170711-2550-object90']
2017-06-05 12:07:24 ANT-120-4_20170605-3000-noodor-noobject
2017-06-05 13:54:39 ANT-120-4_20170605-3000-object180
2017-06-05 14:09:13 ANT-120-4_20170605-3000-object270
[datetime.datetime(2017, 6, 5, 12, 7, 24), datetime.datetime(2017, 6, 5, 13, 54, 39), datetime.datetime(2017, 6, 5, 14, 9, 13)] ['ANT-120-4_20170605-3000-noodor-noobject', 'ANT-120-4_20170605-3000-object180', 'ANT-120-4_20170605-3000-object270']
2017-06-06 11:20:46 ANT-120-4_20170606-3050-noodor-noobject
2017-06-06 13:32:21 ANT-120-4_20170606-3050-object0-foundmoved
2017-06-06 13:18:11 ANT-120-4_20170606-3050-object270
2017-06-06 13:48:22 ANT-120-4_20170606-3050-object90
[datetime.datetime(2017, 6, 6, 11, 20, 46), datetime.datetime(2017, 6, 6, 13, 18, 11), datetime.datetime(2017, 6, 6, 13, 32, 21), datetime.datetime(2017, 6, 6, 13, 48, 22)] ['ANT-120-4_20170606-3050-noodor-noobject', 'ANT-120-4_20170606-3050-object270', 'ANT-120-4_20170606-3050-object0-foundmoved', 'ANT-120-4_20170606-3050-object90']
2017-06-07 10:41:08 ANT-120-4_20170607-3100-noodor-noobject
2017-06-07 13:24:18 ANT-120-4_20170607-3100-object180
2017-06-07 13:07:24 ANT-120-4_20170607-3100-object90
[datetime.datetime(2017, 6, 7, 10, 41, 8), datetime.datetime(2017, 6, 7, 13, 7, 24), datetime.datetime(2017, 6, 7, 13, 24, 18)] ['ANT-120-4_20170607-3100-noodor-noobject', 'ANT-120-4_20170607-3100-object90', 'ANT-120-4_20170607-3100-object180']
2017-06-08 10:20:40 ANT-120-4_20170608-3300-noodor-noobject
2017-06-08 11:24:12 ANT-120-4_20170608-3300-object180
2017-06-08 11:41:24 ANT-120-4_20170608-3300-object270
[datetime.datetime(2017, 6, 8, 10, 20, 40), datetime.datetime(2017, 6, 8, 11, 24, 12), datetime.datetime(2017, 6, 8, 11, 41, 24)] ['ANT-120-4_20170608-3300-noodor-noobject', 'ANT-120-4_20170608-3300-object180', 'ANT-120-4_20170608-3300-object270']
2017-06-09 10:12:55 ANT-120-4_20170609-3350-noodor-noobject
2017-06-09 11:17:17 ANT-120-4_20170609-3350-object180
2017-06-09 11:29:22 ANT-120-4_20170609-3350-object270
[datetime.datetime(2017, 6, 9, 10, 12, 55), datetime.datetime(2017, 6, 9, 11, 17, 17), datetime.datetime(2017, 6, 9, 11, 29, 22)] ['ANT-120-4_20170609-3350-noodor-noobject', 'ANT-120-4_20170609-3350-object180', 'ANT-120-4_20170609-3350-object270']
2017-06-13 13:03:50 ANT-120-4_20170613-2400-noodor-noobject
2017-06-13 13:20:25 ANT-120-4_20170613-2400-object0
2017-06-13 13:42:57 ANT-120-4_20170613-2400-object90
[datetime.datetime(2017, 6, 13, 13, 3, 50), datetime.datetime(2017, 6, 13, 13, 20, 25), datetime.datetime(2017, 6, 13, 13, 42, 57)] ['ANT-120-4_20170613-2400-noodor-noobject', 'ANT-120-4_20170613-2400-object0', 'ANT-120-4_20170613-2400-object90']
2017-06-14 10:39:54 ANT-120-4_20170614-2400-noodor-noobject
2017-06-14 11:03:22 ANT-120-4_20170614-2400-object180
2017-06-14 10:51:33 ANT-120-4_20170614-2400-object90
[datetime.datetime(2017, 6, 14, 10, 39, 54), datetime.datetime(2017, 6, 14, 10, 51, 33), datetime.datetime(2017, 6, 14, 11, 3, 22)] ['ANT-120-4_20170614-2400-noodor-noobject', 'ANT-120-4_20170614-2400-object90', 'ANT-120-4_20170614-2400-object180']
2017-06-15 10:56:21 ANT-120-4_20170615-2400-object180
2017-06-15 11:08:41 ANT-120-4_20170615-2400-object270
[datetime.datetime(2017, 6, 15, 10, 56, 21), datetime.datetime(2017, 6, 15, 11, 8, 41)] ['ANT-120-4_20170615-2400-object180', 'ANT-120-4_20170615-2400-object270']
2017-06-16 11:31:19 ANT-120-4_20170616-2425-noodor-noobject
2017-06-16 12:01:04 ANT-120-4_20170616-2425-object0
2017-06-16 11:49:24 ANT-120-4_20170616-2425-object270
[datetime.datetime(2017, 6, 16, 11, 31, 19), datetime.datetime(2017, 6, 16, 11, 49, 24), datetime.datetime(2017, 6, 16, 12, 1, 4)] ['ANT-120-4_20170616-2425-noodor-noobject', 'ANT-120-4_20170616-2425-object270', 'ANT-120-4_20170616-2425-object0']
2017-06-19 11:23:46 ANT-120-4_20170619-2425-object0
2017-06-19 11:05:58 ANT-120-4_20170619-2425-object270
[datetime.datetime(2017, 6, 19, 11, 5, 58), datetime.datetime(2017, 6, 19, 11, 23, 46)] ['ANT-120-4_20170619-2425-object270', 'ANT-120-4_20170619-2425-object0']
2017-06-20 11:43:56 ANT-120-4_20170620-2425-object0
2017-06-20 11:56:49 ANT-120-4_20170620-2425-object90
[datetime.datetime(2017, 6, 20, 11, 43, 56), datetime.datetime(2017, 6, 20, 11, 56, 49)] ['ANT-120-4_20170620-2425-object0', 'ANT-120-4_20170620-2425-object90']
2017-06-21 11:06:22 ANT-120-4_20170621-2425-object180
2017-06-21 10:51:17 ANT-120-4_20170621-2425-object90
[datetime.datetime(2017, 6, 21, 10, 51, 17), datetime.datetime(2017, 6, 21, 11, 6, 22)] ['ANT-120-4_20170621-2425-object90', 'ANT-120-4_20170621-2425-object180']
2017-06-22 14:11:33 ANT-120-4_20170622-2425-object0
2017-06-22 14:24:12 ANT-120-4_20170622-2425-object90
[datetime.datetime(2017, 6, 22, 14, 11, 33), datetime.datetime(2017, 6, 22, 14, 24, 12)] ['ANT-120-4_20170622-2425-object0', 'ANT-120-4_20170622-2425-object90']
2017-06-23 11:49:43 ANT-120-4_20170623-2400-object180
2017-06-23 11:31:19 ANT-120-4_20170623-2400-object90
[datetime.datetime(2017, 6, 23, 11, 31, 19), datetime.datetime(2017, 6, 23, 11, 49, 43)] ['ANT-120-4_20170623-2400-object90', 'ANT-120-4_20170623-2400-object180']
2017-06-26 13:11:49 ANT-120-4_20170626-2400-noodor-noobject
2017-06-26 13:44:22 ANT-120-4_20170626-2400-object0
2017-06-26 13:27:31 ANT-120-4_20170626-2400-object270
[datetime.datetime(2017, 6, 26, 13, 11, 49), datetime.datetime(2017, 6, 26, 13, 27, 31), datetime.datetime(2017, 6, 26, 13, 44, 22)] ['ANT-120-4_20170626-2400-noodor-noobject', 'ANT-120-4_20170626-2400-object270', 'ANT-120-4_20170626-2400-object0']
2017-06-27 10:17:12 ANT-120-4_20170627-2450-noodor-noobject
2017-06-27 10:29:04 ANT-120-4_20170627-2450-object0
2017-06-27 10:39:49 ANT-120-4_20170627-2450-object90

In [6]:
df_neurofunc['ses_ct'].unique()

array([2, 3, 1, 4, 5, 6, 7], dtype=object)

In [7]:
# print Session where date_time is NaT
print(df_neurofunc[df_neurofunc['date_time'].isna()]['Session'].unique())
print(len(df_neurofunc[df_neurofunc['date_time'].isna()]['Session'].unique()), len(df_neurofunc['Session'].unique()))

[]
0 1345

In [8]:
# df_neurofunc.to_excel('object_complete.xlsx')

In [9]:
# Need to match neurofunc and remapping
import re
from scripts.batch_map.LEC_naming import LEC_naming_format, extract_name_lec

def _check_single_format(filename, fformat, fxn):
    if re.match(str(fformat), str(filename)) is not None:
        return list(fxn(filename))

# For neurofunc need to add extract, date, depth, name, stim 
# iterate thru rows of df_neurofunc and extract from signature
for i, row in df_neurofunc.iterrows():
    # extract
    fname = row['Session']
    
    if 'CAGE' in fname:
        # drop row
        df_neurofunc.drop(i, inplace=True)
    else:
        group, name = extract_name_lec(fname)
        formats = LEC_naming_format[group][name]['object']

        for fformat in list(formats.keys()):
            checked = _check_single_format(fname, fformat, formats[fformat])
            if checked is not None:
                break

        stim, depth, name, date = checked
        
        df_neurofunc.at[i, 'date'] = date
        df_neurofunc.at[i, 'depth'] = str(int(depth))
        df_neurofunc.at[i, 'name'] = name
        df_neurofunc.at[i, 'stim'] = stim

In [10]:
# neurofunc_row_identifiers = ['name','Tetrode', 'Cell ID', 'date', 'depth', 'stim']
# remapping_row_identifiers = ['name','tetrode', 'unit_id', 'date', 'depth','object_location']

# df_remapping_to_merge = df_remapping[df_remapping['score'] == 'whole']

# for row in neurofunc_row_identifiers:
#     df_neurofunc[row] = df_neurofunc[row].astype(str)
# for row in remapping_row_identifiers:
#     df_remapping_to_merge[row] = df_remapping_to_merge[row].astype(str)

# matched_df = None
# for i, row in df_remapping_to_merge.iterrows():
#     # find row in df_neurofunc that mathces using identifiers
#     for j, row2 in df_neurofunc.iterrows():
#         matched = True
#         for k in range(len(neurofunc_row_identifiers)):
#             print('pair ' + str(neurofunc_row_identifiers[k]))
#             print('new2')
#             print(row2[neurofunc_row_identifiers[k]])
#             print('new')
#             print(row[remapping_row_identifiers[k]])
            
#             if row2[neurofunc_row_identifiers[k]] != row[remapping_row_identifiers[k]]:
#                 matched = False

#         # if row2[neurofunc_row_identifiers] == row[remapping_row_identifiers]:
#         if matched == True:
#             if matched_df is None:
#                 row = pd.concat([row, row2], axis=0)
#                 matched_df = row
#             else:
#                 row = pd.concat([row, row2], axis=0)
#                 matched_df = pd.concat([matched_df, row], axis=1)

In [11]:
import pandas as pd

# Define the common columns
neurofunc_row_identifiers = ['name', 'Tetrode', 'Cell ID', 'date', 'depth', 'stim']
remapping_row_identifiers = ['name', 'tetrode', 'unit_id', 'date', 'depth', 'object_location']

for row in neurofunc_row_identifiers:
    df_neurofunc[row] = df_neurofunc[row].astype(str)
for row in remapping_row_identifiers:
    df_remapping[row] = df_remapping[row].astype(str)
df_neurofunc['Session'] = df_neurofunc['Session'].astype(str)
df_remapping['signature'] = df_remapping['signature'].astype(str)

In [12]:

# Create an empty list to store the merged rows
merged_rows = []

# Iterate through each row in df_remapping
for remapping_row in df_remapping.itertuples(index=False):
    # Extract the identifiers from the remapping row
    remapping_identifiers = [getattr(remapping_row, col) for col in remapping_row_identifiers]

    # Find the matching row in df_neurofunc based on the identifiers
    matching_row = df_neurofunc.loc[
        (df_neurofunc[neurofunc_row_identifiers] == remapping_identifiers).all(axis=1)
    ]

    if len(matching_row) > 1:
        # # pick row where neurofunc at column called 'Session' is the same as remapping at 'signature'
        # neurofunc_row_identifiers = ['Session','name', 'Tetrode', 'Cell ID', 'date', 'depth', 'stim']
        # remapping_row_identifiers = ['signature','name', 'tetrode', 'unit_id', 'date', 'depth', 'object_location']
        # remapping_identifiers = [getattr(remapping_row, col) for col in remapping_row_identifiers]

        # # Find the matching row in df_neurofunc based on the identifiers
        # matching_row = df_neurofunc.loc[
        #     (df_neurofunc[neurofunc_row_identifiers] == remapping_identifiers).all(axis=1)
        # ]
        # print('new')
        # print(len(matching_row))
        remapping_row_ses_ct = int(remapping_row[7].split('_')[-1])
        # print(matching_row['ses_ct'] == remapping_row_ses_ct, matching_row['ses_ct'], remapping_row_ses_ct)
        matching_row = matching_row[matching_row['ses_ct'] == remapping_row_ses_ct]


    # Check if a matching row was found
    if len(matching_row) == 0:
        print("Found {} matching rows for {}".format(len(matching_row), remapping_identifiers))
        print(matching_row['Session'], getattr(remapping_row, 'signature'))
        # stop()
    elif len(matching_row) > 1:
        # check all rows are matching on spatial info score 
        prev = None
        for i, row in matching_row.iterrows():
            if prev is None:
                prev = row['spike_count']
            else:
                if prev != row['spike_count']:
                    print('multiple matches')
                    print(matching_row)
                    # stop()
        
    # Join the matching rows
    # merged_row = pd.concat([matching_row, pd.DataFrame([remapping_row], columns=df_remapping.columns)], axis=1)
    merged_rows.append(matching_row)

# Create the merged dataframe
merged_df = pd.concat(merged_rows, ignore_index=True)

# Print the merged dataframe
# print(merged_df)

Found 0 matching rows for ['ANT-135a-7', '7', '2', '20180611', '3125', '270']
Series([], Name: Session, dtype: object) ANT-135a-7_20180611-ROUND-3125-270
Found 0 matching rows for ['ANT-135a-7', '7', '2', '20180611', '3125', '270']
Series([], Name: Session, dtype: object) ANT-135a-7_20180611-ROUND-3125-270
Found 0 matching rows for ['ANT-135a-7', '7', '2', '20180611', '3125', '270']
Series([], Name: Session, dtype: object) ANT-135a-7_20180611-ROUND-3125-270
Found 0 matching rows for ['ANT-135a-7', '7', '2', '20180611', '3125', '270']
Series([], Name: Session, dtype: object) ANT-135a-7_20180611-ROUND-3125-270
Found 0 matching rows for ['ANT-135a-7', '7', '2', '20180611', '3125', '270']
Series([], Name: Session, dtype: object) ANT-135a-7_20180611-ROUND-3125-270
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', '180']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-180
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', '180']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-180
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', '180']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-180
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', '180']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-180
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', '180']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-180
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', '180']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-180
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', '180']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-180
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', '180']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-180
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', 'NO']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-NO-2
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', 'NO']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-NO-2
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', 'NO']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-NO-2
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', 'NO']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-NO-2
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', 'NO']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-NO-2
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', 'NO']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-NO-2
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', 'NO']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-NO-2
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', 'NO']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-NO-2
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', '180']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-180-2
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', '180']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-180-2
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', '180']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-180-2
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', '180']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-180-2
Found 0 matching rows for ['ANT-135a-7', '6', '5', '20180620', '3300', '180']
Series([], Name: Session, dtype: object) ANT-135a-7_20180620-ROUND-3300-180-2
Found 0 matching rows for ['ANT-135a-7', '7', '1', '20180621', '3300', '90']
Series([], Name: Session, dtype: object) ANT-135a-7_20180621-ROUND-3300-90
Found 0 matching rows for ['ANT-135a-7', '7', '1', '20180621', '3300', '90']
Series([], Name: Session, dtype: object) ANT-135a-7_20180621-ROUND-3300-90
Found 0 matching rows for ['ANT-135a-7', '7', '1', '20180621', '3300', '90']
Series([], Name: Session, dtype: object) ANT-135a-7_20180621-ROUND-3300-90
Found 0 matching rows for ['ANT-135a-7', '7', '1', '20180621', '3300', '90']
Series([], Name: Session, dtype: object) ANT-135a-7_20180621-ROUND-3300-90
Found 0 matching rows for ['ANT-135a-7', '7', '1', '20180621', '3300', '90']
Series([], Name: Session, dtype: object) ANT-135a-7_20180621-ROUND-3300-90
Found 0 matching rows for ['ANT-135a-7', '7', '1', '20180625', '3300', '90']
Series([], Name: Session, dtype: object) ANT-135a-7_20180625-ROUND-3300-90-2
Found 0 matching rows for ['ANT-135a-7', '7', '1', '20180625', '3300', '90']
Series([], Name: Session, dtype: object) ANT-135a-7_20180625-ROUND-3300-90-2
Found 0 matching rows for ['ANT-135a-7', '7', '1', '20180625', '3300', '90']
Series([], Name: Session, dtype: object) ANT-135a-7_20180625-ROUND-3300-90-2
Found 0 matching rows for ['ANT-135a-7', '7', '1', '20180625', '3300', '90']
Series([], Name: Session, dtype: object) ANT-135a-7_20180625-ROUND-3300-90-2
Found 0 matching rows for ['ANT-135a-7', '7', '1', '20180625', '3300', '90']
Series([], Name: Session, dtype: object) ANT-135a-7_20180625-ROUND-3300-90-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', '180']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-180-2
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', '180']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-180-2
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', '180']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-180-2
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', '180']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-180-2
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', '180']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-180-2
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', '180']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-180-2
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', '180']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-180-2
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', '180']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-180-2
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-90-2
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-90-2
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-90-2
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-90-2
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-90-2
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', 'NO']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-NO-2
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', 'NO']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-NO-2
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', 'NO']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-NO-2
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', 'NO']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-NO-2
Found 0 matching rows for ['ANT-140-4', '1', '5', '20180706', '3350', 'NO']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-NO-2
Found 0 matching rows for ['ANT-140-4', '6', '2', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '6', '2', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '6', '2', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '6', '2', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '6', '2', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '6', '2', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '6', '2', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '6', '2', '20180706', '3350', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-270
Found 0 matching rows for ['ANT-140-4', '6', '2', '20180706', '3350', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-90-2
Found 0 matching rows for ['ANT-140-4', '6', '2', '20180706', '3350', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-90-2
Found 0 matching rows for ['ANT-140-4', '6', '2', '20180706', '3350', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-90-2
Found 0 matching rows for ['ANT-140-4', '6', '2', '20180706', '3350', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-90-2
Found 0 matching rows for ['ANT-140-4', '6', '2', '20180706', '3350', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180706-ROUND-3350-90-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180705', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180705', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180705', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180705', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180705', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180705', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180705', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180705', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-270
Found 0 matching rows for ['ANT-140-4', '6', '1', '20180705', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-270
Found 0 matching rows for ['ANT-140-4', '6', '1', '20180705', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-270
Found 0 matching rows for ['ANT-140-4', '6', '1', '20180705', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-270
Found 0 matching rows for ['ANT-140-4', '6', '1', '20180705', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-270
Found 0 matching rows for ['ANT-140-4', '6', '1', '20180705', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-270
Found 0 matching rows for ['ANT-140-4', '6', '1', '20180705', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-270
Found 0 matching rows for ['ANT-140-4', '6', '1', '20180705', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-270
Found 0 matching rows for ['ANT-140-4', '6', '1', '20180705', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-270
Found 0 matching rows for ['ANT-140-4', '6', '1', '20180705', '3300', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-90-2
Found 0 matching rows for ['ANT-140-4', '6', '1', '20180705', '3300', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-90-2
Found 0 matching rows for ['ANT-140-4', '6', '1', '20180705', '3300', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-90-2
Found 0 matching rows for ['ANT-140-4', '6', '1', '20180705', '3300', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-90-2
Found 0 matching rows for ['ANT-140-4', '6', '1', '20180705', '3300', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-90-2
Found 0 matching rows for ['ANT-140-4', '6', '1', '20180705', '3300', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-90-2
Found 0 matching rows for ['ANT-140-4', '6', '1', '20180705', '3300', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-90-2
Found 0 matching rows for ['ANT-140-4', '6', '1', '20180705', '3300', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180705-ROUND-3300-90-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180703', '3300', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180703-ROUND-3300-90-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180703', '3300', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180703-ROUND-3300-90-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180703', '3300', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180703-ROUND-3300-90-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180703', '3300', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180703-ROUND-3300-90-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180703', '3300', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180703-ROUND-3300-90-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180703', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180703-ROUND-3300-270-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180703', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180703-ROUND-3300-270-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180703', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180703-ROUND-3300-270-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180703', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180703-ROUND-3300-270-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180703', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180703-ROUND-3300-270-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180703', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180703-ROUND-3300-270-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180703', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180703-ROUND-3300-270-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180703', '3300', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180703-ROUND-3300-270-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180702', '3250', 'NO']
Series([], Name: Session, dtype: object) ANT-140-4_20180702-ROUND-3250-NO
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180702', '3250', 'NO']
Series([], Name: Session, dtype: object) ANT-140-4_20180702-ROUND-3250-NO
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180702', '3250', 'NO']
Series([], Name: Session, dtype: object) ANT-140-4_20180702-ROUND-3250-NO
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180702', '3250', 'NO']
Series([], Name: Session, dtype: object) ANT-140-4_20180702-ROUND-3250-NO
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180702', '3250', 'NO']
Series([], Name: Session, dtype: object) ANT-140-4_20180702-ROUND-3250-NO
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180702', '3250', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180702-ROUND-3250-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180702', '3250', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180702-ROUND-3250-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180702', '3250', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180702-ROUND-3250-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180702', '3250', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180702-ROUND-3250-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180702', '3250', '270']
Series([], Name: Session, dtype: object) ANT-140-4_20180702-ROUND-3250-270
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180702', '3250', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180702-ROUND-3250-90-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180702', '3250', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180702-ROUND-3250-90-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180702', '3250', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180702-ROUND-3250-90-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180702', '3250', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180702-ROUND-3250-90-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180702', '3250', '90']
Series([], Name: Session, dtype: object) ANT-140-4_20180702-ROUND-3250-90-2
Found 0 matching rows for ['ANT-140-4', '1', '1', '20180702', '3250', '90']

In [13]:
remapping_identifiers = [getattr(remapping_row, col) for col in remapping_row_identifiers]

    # Find the matching row in df_neurofunc based on the identifiers
matching_row = df_neurofunc.loc[
        (df_neurofunc[neurofunc_row_identifiers] == remapping_identifiers).all(axis=1)
    ]

In [14]:
remapping_identifiers

['B6-LEC2', '4', '7', '20151216', '3475', '90']

In [15]:
df_neurofunc['ses_ct'].unique()

array([2, 3, 1, 4, 5, 6, 7], dtype=object)

In [16]:
df_remapping['session_id'].unique()

array(['session_2', 'session_3', 'session_1', 'session_4', 'session_5',
       'session_6', 'session_7'], dtype=object)

In [17]:
matching_row

,Unnamed: 0,Session,Tetrode,Cell ID,spike_width,spike_count,firing_rate,Avg. Spikes/Burst,bursting,iso_dist,...,Field_6,group,Field_7,Field_8,date_time,ses_ct,date,depth,name,stim
26443,26.0,B6-LEC2_20151216-0-90,4,7,0.000292,381,0.317236,1.999025,0.000000,2.487047,...,NaN,B6,NaN,NaN,2015-12-16 11:13:08,1,20151216,3475,B6-LEC2,90
26470,53.0,B6-LEC2_20151216-0-90_2,4,7,0.000292,385,0.320566,2.000000,0.260417,2.506928,...,NaN,B6,NaN,NaN,2015-12-16 11:13:08,2,20151216,3475,B6-LEC2,90

In [18]:
remapping_row[7]

'session_2'

In [19]:
print(df_neurofunc.shape, df_remapping.shape, merged_df.shape)

(26533, 44) (120475, 46) (119414, 44)

In [20]:
merged_df

,Unnamed: 0,Session,Tetrode,Cell ID,spike_width,spike_count,firing_rate,Avg. Spikes/Burst,bursting,iso_dist,...,Field_6,group,Field_7,Field_8,date_time,ses_ct,date,depth,name,stim
0,46.0,ANT-119a-6_20170605-3050-270,1,1,0.000083,2626,4.369384,2.471698,14.735867,18.513673,...,NaN,ANT,NaN,NaN,2017-06-05 14:28:49,2,20170605-3050-270,3050,ANT-119a-6,270
1,46.0,ANT-119a-6_20170605-3050-270,1,1,0.000083,2626,4.369384,2.471698,14.735867,18.513673,...,NaN,ANT,NaN,NaN,2017-06-05 14:28:49,2,20170605-3050-270,3050,ANT-119a-6,270
2,46.0,ANT-119a-6_20170605-3050-270,1,1,0.000083,2626,4.369384,2.471698,14.735867,18.513673,...,NaN,ANT,NaN,NaN,2017-06-05 14:28:49,2,20170605-3050-270,3050,ANT-119a-6,270
3,46.0,ANT-119a-6_20170605-3050-270,1,1,0.000083,2626,4.369384,2.471698,14.735867,18.513673,...,NaN,ANT,NaN,NaN,2017-06-05 14:28:49,2,20170605-3050-270,3050,ANT-119a-6,270
4,46.0,ANT-119a-6_20170605-3050-270,1,1,0.000083,2626,4.369384,2.471698,14.735867,18.513673,...,NaN,ANT,NaN,NaN,2017-06-05 14:28:49,2,20170605-3050-270,3050,ANT-119a-6,270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119409,53.0,B6-LEC2_20151216-0-90_2,4,7,0.000292,385,0.320566,2.000000,0.260417,2.506928,...,NaN,B6,NaN,NaN,2015-12-16 11:13:08,2,20151216,3475,B6-LEC2,90
119410,53.0,B6-LEC2_20151216-0-90_2,4,7,0.000292,385,0.320566,2.000000,0.260417,2.506928,...,NaN,B6,NaN,NaN,2015-12-16 11:13:08,2,20151216,3475,B6-LEC2,90
119411,53.0,B6-LEC2_20151216-0-90_2,4,7,0.000292,385,0.320566,2.000000,0.260417,2.506928,...,NaN,B6,NaN,NaN,2015-12-16 11:13:08,2,20151216,3475,B6-LEC2,90
119412,53.0,B6-LEC2_20151216-0-90_2,4,7,0.000292,385,0.320566,2.000000,0.260417,2.506928,...,NaN,B6,NaN,NaN,2015-12-16 11:13:08,2,20151216,3475,B6-LEC2,90
119413,53.0,B6-LEC2_20151216-0-90_2,4,7,0.000292,385,0.320566,2.000000,0.260417,2.506928,...,NaN,B6,NaN,NaN,2015-12-16 11:13:08,2,20151216,3475,B6-LEC2,90